name: Deploy to Netlify with Terraform

on:
  push:
    branches:
      - main   # Runs whenever you push to main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out repo code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6   # or your version

      # Step 3: Terraform Init
      - name: Terraform Init
        run: terraform init

      # Step 4: Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # Step 5: Terraform Apply (auto approve)
      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
